<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'Para bajar la photo, pulse aqui o desplace la photo en est cuadro',
    'CROP_PHOTO' => 'Recortar la photo',
    'DELETE_PHOTO' => 'Suprimir photo',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Poroblema : no se puede bajar esta photo',
    'MISSING_ATTRIBUTE' => 'El attibuto "{attribute}" tiene que ser especificado',
    'ONLY_POST_REQUEST' => 'Solamente pedidos en POST-request',
    'UPLOAD_ANOTHER_PHOTO' => 'Subir otra photo',
    'TOO_BIG_ERROR' => 'Excedió la talla permisible del fichero ({size} Mb)',
    'EXTENSION_ERROR' => 'Solamente se pueden subir estos formatos: {formats}'
];
