<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'クリックして画像ファイルを選択、または、画像ファイルをここにドラッグ',
    'CROP_PHOTO' => '画像を切り抜き',
    'DELETE_PHOTO' => '画像を消去',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'ファイルをアップロード出来ません',
    'MISSING_ATTRIBUTE' => '"{attribute}" は必須です',
    'ONLY_POST_REQUEST' => 'POST リクエストのみ許可されています',
    'UPLOAD_ANOTHER_PHOTO' => '別の画像をアップロード',
    'TOO_BIG_ERROR' => '許可されているファイル・サイズ({size} Mb)を超過しています',
    'EXTENSION_ERROR' => '以下のファイル形式だけが許可されています: {formats}'
];
