<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'Pour ajouter une photo cliquez ici ou déplacez la photo',
    'CROP_PHOTO' => 'Rogner la photo',
    'DELETE_PHOTO' => 'Effacer la photo',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Impossible de télécharger la photo',
    'MISSING_ATTRIBUTE' => 'L\'attibut "{attribute}" doit être spécifié',
    'ONLY_POST_REQUEST' => 'Seulement les requêtes POST-request sont admises',
    'UPLOAD_ANOTHER_PHOTO' => 'Charger une autre photo',
    'TOO_BIG_ERROR' => 'Dépassement de la taille limite permise du fichier : ({size} Mb)',
    'EXTENSION_ERROR' => 'Seuls ces formats sont admis: {formats}'
];
