<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'Bild Datei hier hineinziehen oder clicken und auswählen',
    'CROP_PHOTO' => 'Bild zuschneiden',
    'DELETE_PHOTO' => 'Bild löschen',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Datei kann nicht hochgeladen werden',
    'MISSING_ATTRIBUTE' => 'Attibut "{attribute}" muss spezifiziert sein',
    'ONLY_POST_REQUEST' => 'Nur POST-Anfragen erlaubt',
    'UPLOAD_ANOTHER_PHOTO' => 'Anderes Bild hochladen',
    'TOO_BIG_ERROR' => 'Datei überschreitet die erlaubte Größe von ({size} Mb)',
    'EXTENSION_ERROR' => 'Lediglich die folgenden Formate sind zulässig: {formats}'
];
