<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DEFAULT_LABEL' => 'Для завантаження гового фото, натисніть тут або перетащіть файл сюди',
    'CROP_PHOTO' => 'Обрізати фото',
    'DELETE_PHOTO' => 'Видалити фото',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Неможливо завантажити файл',
    'MISSING_ATTRIBUTE' => 'Атрибут "{attribute}" повинен бути вказаний',
    'ONLY_POST_REQUEST' => 'Допустимий лише POST-запит',
    'UPLOAD_ANOTHER_PHOTO' => 'Завантажити інше фото',
    'TOO_BIG_ERROR' => 'Максимальний розмір фала перевищений ({size} Мб)',
    'EXTENSION_ERROR' => 'Дозволені лише наступні формати файлів: {formats}'
];
